name: PR

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
  
  comment:
    if: ${{ github.event.pull_request.user.login == 'dependabot' }}
    env:
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
