name: PR

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
