name: PR

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
  
  comment:
    env:
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR author $PR_AUTHOR"
      - uses: actions/github-script@v6
        if: ${{ github.event.pull_request.user.login == 'dependabot' }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo PR author
      run: echo "The author of this PR is ${{ github.event.pull_request.user.login }}"
